repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: local
    hooks:
      - id: make
        name: make test
        entry: make format lint-fix test
        language: system
        pass_filenames: false
        always_run: true
