repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: local
    hooks:
      - id: formt
        name: make formt
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
      - id: lint-fix
        name: make lint-fix
        entry: make lint-fix
        language: system
        pass_filenames: false
        always_run: true
      - id: docs-check
        name: make docs-check
        entry: make docs-check
        language: system
        pass_filenames: false
        always_run: true
      - id: test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true