name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GIT_COMMITTER_NAME: github-actions[bot] 
  GIT_COMMITTER_EMAIL: ci-bot@example.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Do Make
      run: uv run make test
    - name: Do Mike
      run: |
        git fetch origin gh-pages --depth=1
        uv run mike deploy --push devel
